- hosts: all
  remote_user: root
  tasks:
    - name: Clone
      git:
        repo: https://github.com/ballometer/api-weather.git
        dest: /root/api-weather

    - name: Copy service file
      ansible.builtin.copy:
        src: rootfs-overlay/etc/systemd/system/api-weather.service
        dest: /etc/systemd/system/api-weather.service

    - name: Install npm packages
      community.general.npm:
        path: /root/api-weather
        ci: yes

    - name: Check service is running
      ansible.builtin.systemd:
        state: started
        name: api-weather
