- hosts: all
  remote_user: root
  tasks:
    - name: Clone
      git:
        repo: https://github.com/ballometer/api-auth.git
        dest: /root/api-auth

    - name: Create service file
      ansible.builtin.template:
        src: rootfs-overlay/etc/systemd/system/api-auth.service.j2
        dest: /etc/systemd/system/api-auth.service

    - name: Copy users.json if absent
      ansible.builtin.copy:
        src: rootfs-overlay/root/api-auth/users.json
        dest: /root/api-auth/users.json
        force: no

    - name: Install npm packages
      community.general.npm:
        path: /root/api-auth

    - name: Check service is running
      ansible.builtin.systemd:
        state: started
        name: api-auth
