- hosts: all
  remote_user: root
  tasks:
    - name: Clone
      git:
        repo: https://github.com/ballometer/api-auth.git
        dest: /root/api-auth

    - name: Copy api-auth.service
      ansible.builtin.copy:
        src: rootfs-overlay/etc/systemd/system/api-auth.service
        dest: /etc/systemd/system/api-auth.service

    - name: Inject JWT_SECRET
      ansible.builtin.replace:
        path: /etc/systemd/system/api-auth.service
        regexp: 'JWT_SECRET'
        replace: "{{ JWT_SECRET }}"

    - name: Create empty users.json
      ansible.builtin.lineinfile:
        path: /root/api-auth/users.json
        line: "[]"
        create: yes

    - name: Check service is running
      ansible.builtin.systemd:
        state: started
        name: api-auth
