- hosts: all
  remote_user: root
  tasks:    
    - name: Copy /etc/grafana/grafana.ini
      ansible.builtin.copy:
        src: rootfs-overlay/etc/grafana/grafana.ini
        dest: /etc/grafana/grafana.ini

    - name: Check grafana is running
      ansible.builtin.systemd:
        state: started
        name: grafana-server
  