- hosts: all
  remote_user: root
  tasks:    
    - name: Check influxdb is running
      ansible.builtin.systemd:
        state: started
        name: influxdb

    - name: Create database ballometer
      ansible.builtin.shell: influx -execute 'CREATE DATABASE ballometer'

    - name: Create database weather
      ansible.builtin.shell: influx -execute 'CREATE DATABASE weather'

    - name: Download from remote to github
      ansible.posix.synchronize:
        mode: pull
        src: /root/influx/influx-backup
        dest: influx-backup
    
