- hosts: all
  remote_user: root
  tasks:
    - name: Copy sites-available
      ansible.builtin.copy:
        src: rootfs-overlay/etc/nginx/sites-available/{{item}}ballometer.io
        dest: /etc/nginx/sites-available/{{item}}ballometer.io
      loop:
        - api.
        - tiles.
        - grafana.
        - ""

    - name: Enable sites
      file:
        src: /etc/nginx/sites-available/{{item}}ballometer.io
        dest: /etc/nginx/sites-enabled/{{item}}ballometer.io
        state: link
      loop:
        - api.
        - tiles.
        - grafana.
        - ""

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
