- hosts: all
  remote_user: root
  tasks:
    - name: Download planet.mbtiles
      ansible.builtin.shell: wget -c "{{ MBTILES_URL }}" -O "{{ VOLUME_PATH }}planet.mbtiles"
      args:
        creates: "{{ VOLUME_PATH }}planet.mbtiles"
