- hosts: all
  remote_user: root
  tasks:    
    - name: Download planet.mbtiles
      get_url:
        url: "{{ MBTILES_URL }}"
        dest: "{{ VOLUME_PATH }}planet.mbtiles"
        tmp_dest: "{{ VOLUME_PATH }}planet.mbtiles"
