- hosts: all
  remote_user: root
  tasks:
    - name: ufw default deny incoming
      community.general.ufw:
        default: deny
        direction: incoming

    - name: ufw default allow outgoing
      community.general.ufw:
        default: allow
        direction: outgoing

    - name: ufw allow OpenSSH
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: ufw allow 'Nginx Full'
      community.general.ufw:
        rule: allow
        name: 'Nginx Full'

    - name: ufw delete allow 'Nginx HTTP'
      community.general.ufw:
        rule: allow
        name: 'Nginx HTTP'
        delete: yes
    
    - name: ufw enable
      community.general.ufw:
        state: enabled
