- hosts: all
  remote_user: root
  tasks:
    - name: ufw default deny incoming
      community.general.ufw:
        default: deny
        direction: incoming

    - name: ufw default allow outgoing
      community.general.ufw:
        default: allow
        direction: outgoing

    - name: ufw allow ssh, 80, 443
      community.general.ufw:
        rule: allow
        port: "{{item}}"
      loop:
        - ssh
        - 80
        - 443
    
    - name: ufw enable
      community.general.ufw:
        state: enabled     
