name: ssh

on: push

jobs:
  ssh:
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
    - uses: actions/checkout@v2
    - name: Add SSH key
      run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan ${{ secrets.HOST_IP }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install ansible
      run: pip install ansible
    
    - name: Ansible apt.yml
      run: ansible-playbook -i ${{ secrets.HOST_IP }}, apt.yml

    - name: Ansible ufw.yml
      run: ansible-playbook -i ${{ secrets.HOST_IP }}, ufw.yml

    - name: Ansible grafana.yml
      run: ansible-playbook -i ${{ secrets.HOST_IP }}, grafana.yml
